apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2gb
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: job-storage
  hostPath:
    path: /data/pv-2gb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storage
  hostPath:
    path: /data/postgres